spring:
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
    username: gcaio7463@gmail.com
    password: myqbjolchtkeyqqz